[package]
name = "ntex-amqp"
version = "0.3.0-b.3"
authors = ["ntex contributors <team@ntex.rs>"]
description = "AMQP 1.0 Client/Server framework"
documentation = "https://docs.rs/ntex-amqp"
repository = "https://github.com/ntex/ntex-amqp.git"
categories = ["network-programming"]
keywords = ["AMQP", "IoT", "messaging"]
license = "MIT"
exclude = [".gitignore", ".travis.yml", ".cargo/config"]
edition = "2018"

[workspace]
members = [
  ".",
  "codec",
]

[features]
default = []

# log frames on trace level
frame-trace = []

[dependencies]
ntex = "0.2.0-b.5"
ntex-amqp-codec = "0.4.0-b.1"
ntex-router = "0.3.8"

ahash = "0.6.3"
bitflags = "1.2.1"
bytes = "0.5.6"
bytestring = "0.1.5"
derive_more = "0.99.11"
either = "1.6.1"
futures = "0.3.12"
log = "0.4"
pin-project-lite = "0.2.4"
slab = "0.4"
uuid = { version = "0.8", features = ["v4"] }

[dev-dependencies]
env_logger = "0.8"

[patch.crates-io]
ntex-amqp = { path = "." }
ntex-amqp-codec = { path = "codec" }
