[package]
name = "amqp1"
version = "0.1.0"
authors = ["Mike Yagley <myagley@gmail.com>"]

[dependencies]
bytes = "0.4"
chrono = "0.4"
uuid = { version = "0.6", features = ["use_std", "v4"] }
ordered-float = "0.5"
error-chain = "0.11"
tokio-io = "0.1"
tokio-core = "0.1"
futures-await = "0.1.1"

[build-dependencies]
handlebars = { version = "0.27", optional = true }
serde        = { version = "1.0", optional = true }
serde_derive = { version = "1.0", optional = true }
serde_json   = { version = "1.0", optional = true }
lazy_static  = { version = "1.0", optional = true }
regex = { version = "1.0", optional = true }


[dev-dependencies]
native-tls = "0.1"
tokio-tls = "0.1"
hex-slice = { git = 'https://github.com/g2p/hex-slice', branch = 'flags' }

[features]
from-spec = ["handlebars", "serde", "serde_derive", "serde_json", "lazy_static", "regex"]