[package]
name = "actix-amqp"
version = "0.1.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
documentation = "https://docs.rs/actix-amqp"
repository = "https://github.com/actix/actix-amqp.git"
categories = ["network-programming"]
keywords = ["AMQP", "IoT", "messaging"]
license = "MIT/Apache-2.0"
exclude = [".gitignore", ".travis.yml", ".cargo/config"]
edition = "2018"

[workspace]
members = [
  ".",
  "codec",
]

[dependencies]
amqp-codec = "0.1.0"

actix-codec = "0.1.2"
actix-service = "0.4.0"
actix-connect = "0.2.0"
actix-router = "0.1.2"
actix-utils = "0.4.0"
actix-server-config = "0.1.1"

derive_more = "0.15"
either = "1.5.2"
futures = "0.1.26"
hashbrown = "0.5.0"
http = "0.1.16"
log = "0.4"
bytes = "0.4"
uuid = { version = "0.7", features = ["v4"] }
slab = "0.4"
string = "0.2.1"
tokio-timer = "0.2.8"
tokio-current-thread = "0.1.5"

[dev-dependencies]
env_logger = "0.6"
actix-test-server = "0.2.2"

[patch.crates-io]
actix-amqp = { path = "." }
amqp-codec = { path = "codec" }