[package]
name = "amqp-transport"
version = "0.1.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
edition = "2018"

[dependencies]
amqp-codec = { git = "https://github.com/fafhrd91/amqp-codec.git" }

actix-codec = "0.1.0"
actix-service = "0.1.3"
actix-connector = "0.1.1"
actix-router = { git = "https://github.com/actix/actix-net.git" }
actix-utils = "0.1.0"
derive_more = "0.13"
either = "1.5"
futures = "0.1"
hashbrown = "0.1.8"
log = "0.4"
bytes = "0.4"
uuid = { version = "0.7", features = ["v4"] }
slab = "0.4"
string = "0.1.3"
tokio-timer = "0.2"

[dev-dependencies]
env_logger = "0.5"
actix-test-server = { git = "https://github.com/actix/actix-net.git" }

[patch.crates-io]
actix-utils = { git = "https://github.com/actix/actix-net.git" }
