[package]
name = "amqp-codec"
version = "0.1.0"
description = "AMQP 1.0 Protocol Codec"
authors = ["Mike Yagley <myagley@gmail.com>", "Max Gortman <mgortman@microsoft.com>", "Nikolay Kim <fafhrd91@gmail.com>"]
edition = "2018"

[dependencies]
bytes = "0.4"
chrono = "0.4"
derive_more = "0.14"
hashbrown = "0.1.8"
ordered-float = "1.0"
string = "0.1.3"
tokio-io = "0.1"
tokio-codec = "0.1"
uuid = { version = "0.7", features = ["v4"] }

[build-dependencies]
handlebars = { version = "0.27", optional = true }
serde        = { version = "1.0", optional = true }
serde_derive = { version = "1.0", optional = true }
serde_json   = { version = "1.0", optional = true }
lazy_static  = { version = "1.0", optional = true }
regex = { version = "1.0", optional = true }

[features]
default = []

from-spec = ["handlebars", "serde", "serde_derive", "serde_json", "lazy_static", "regex"]
