[package]
name = "amqp"
version = "0.1.0"
description = "AMQP1 protocol codec"
authors = ["Mike Yagley <myagley@gmail.com>"]
edition = "2018"

[dependencies]
bytes = "0.4"
chrono = "0.4"
derive_more = "0.13"
ordered-float = "0.5"
string = "0.1"
tokio-io = "0.1"
tokio-codec = "0.1"
uuid = { version = "0.7", features = ["v4"] }

[build-dependencies]
handlebars = { version = "0.27", optional = true }
serde        = { version = "1.0", optional = true }
serde_derive = { version = "1.0", optional = true }
serde_json   = { version = "1.0", optional = true }
lazy_static  = { version = "1.0", optional = true }
regex = { version = "1.0", optional = true }

[features]
default = []

from-spec = ["handlebars", "serde", "serde_derive", "serde_json", "lazy_static", "regex"]
