[package]
name = "ntex-amqp"
version = "0.2.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
description = "AMQP 1.0 Client/Server framework"
documentation = "https://docs.rs/actix-amqp"
repository = "https://github.com/actix/actix-amqp.git"
categories = ["network-programming"]
keywords = ["AMQP", "IoT", "messaging"]
license = "MIT"
exclude = [".gitignore", ".travis.yml", ".cargo/config"]
edition = "2018"

[workspace]
members = [
  ".",
  "codec",
]

[dependencies]
ntex = "0.1.1"
ntex-amqp-codec = "0.1.0"
ntex-router = "0.3"
ntex-codec = "0.1.0"

bytes = "0.5.3"
bytestring = "0.1.4"
derive_more = "0.99.5"
either = "1.5.3"
futures = "0.3.1"
fxhash = "0.2.1"
http = "0.2.0"
log = "0.4"
pin-project = "0.4.6"
uuid = { version = "0.8", features = ["v4"] }
slab = "0.4"

[dev-dependencies]
env_logger = "0.6"

[patch.crates-io]
ntex-amqp = { path = "." }
ntex-amqp-codec = { path = "codec" }

ntex = { git = "https://github.com/ntex-rs/ntex.git" }
ntex-rt = { git = "https://github.com/ntex-rs/ntex.git" }
ntex-codec = { git = "https://github.com/ntex-rs/ntex.git" }
ntex-router = { git = "https://github.com/ntex-rs/ntex.git" }
ntex-macros = { git = "https://github.com/ntex-rs/ntex.git" }
ntex-web-macros = { git = "https://github.com/ntex-rs/ntex.git" }
ntex-service = { git = "https://github.com/ntex-rs/ntex.git" }
