[package]
name = "actix-amqp"
version = "0.1.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
description = "AMQP 1.0 Client/Server framework"
documentation = "https://docs.rs/actix-amqp"
repository = "https://github.com/actix/actix-amqp.git"
categories = ["network-programming"]
keywords = ["AMQP", "IoT", "messaging"]
license = "MIT/Apache-2.0"
exclude = [".gitignore", ".travis.yml", ".cargo/config"]
edition = "2018"

[workspace]
members = [
  ".",
  "codec",
]

[dependencies]
amqp-codec = "0.1.0"

actix-codec = "0.2.0"
actix-service = "1.0.0"
actix-connect = "1.0.0"
actix-router = "0.2.0"
actix-utils = "1.0.1"
actix-rt = "1.0.0"

bytes = "0.5.2"
bytestring = "0.1.1"
derive_more = "0.99.2"
either = "1.5.2"
futures = "0.3.1"
fxhash = "0.2.1"
http = "0.2.0"
log = "0.4"
pin-project = "0.4.6"
uuid = { version = "0.8", features = ["v4"] }
slab = "0.4"

[dev-dependencies]
env_logger = "0.6"
actix-testing = "1.0.0"

[patch.crates-io]
actix-amqp = { path = "." }
amqp-codec = { path = "codec" }
